export const CALL_ERR_AUDIO_DURATION = 4000
export const MIN_CHUNK_DURATION = 5000
export const MAX_CHUNK_DURATION = 30000

export const ANALIZER_POLL_INTERVAL = 200
export const ANALIZER_ALERT_QUANTILE = 0.3
export const ANALIZER_STORE_COUNT = 150
