export const CALL_ERR_AUDIO_DURATION = 4000
export const MIN_CHUNK_DURATION = 5000
export const MAX_CHUNK_DURATION = 30000

export const ANALIZER_POLL_INTERVAL = 200
export const ANALIZER_ALERT_SEQ = 3
export const ANALIZER_ALERT_MULTIPLICATOR = 3
export const ANALIZER_STORE_COUNT = 3
export const ANALIZER_STORE_SILENCE_COUNT = 150

export const CHUNK_MIME_TYPE = "audio/webm;"
export const DATA_CHANNEL_NAME = "WEBRTC_CHANNEL"
