export const CALL_ERR_AUDIO_DURATION = 4000
export const MIN_CHUNK_DURATION = 5000
export const MAX_CHUNK_DURATION = 30000

export const ANALIZER_FFT = 512
export const ANALIZER_MIN_DB = -127
export const ANALIZER_MAX_DB = 0
export const ANALIZER_SMOOTH = 0.3
export const ANALIZER_POLL_INTERVAL = 200

export const ANALIZER_ALERT_QUANTILE = 0.15
export const ANALIZER_LAST_BINS_SIZE = 150
export const ABSOLUTE_SILENCE_LEVEL_PERC = 10
